Milestone 3
sediqullahbadakhsh/awesome-books pull request #4
Opened 2022-02-08 20:13 UTC by Estebanmual

2022-02-08 23:10 UTC, rloterh requested changes
Hi Esteban & Sediq, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- Descriptive Pull Request
- Site navigation is working correctly
- Good ReadMe
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 23:10 UTC, rloterh commented on index.html
> +        </div>
- [x] To enhance the user experience of this application kindly ensure that an **active menu link is highlighted**(color change or change in opacity). In other words, the current active page should have the corresponding menu item highlighted, as can be seen in the provided [wireframe design](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m4_full_website.md). Kindly ensure to improve upon this aspect in your design, as we really want our designs to as much as possible mimic the provided wireframe template.

**Your nav menu:**
![image](https://user-images.githubusercontent.com/12745474/153089472-dae36ddb-4118-481e-ba4b-a53b3b102053.png)


**The wireframe nav menu:**
![image](https://user-images.githubusercontent.com/12745474/138342596-c4a68582-914a-4c5a-b255-8db0325cbaca.png)

2022-02-08 23:10 UTC, rloterh commented on index.html
>          <table class="table">
- [ ] The styling of your _books list rows_ background color does not conform to the database table alternate rows color, as can be seen in the original wireframe below. Kindly ensure to improve upon this aspect.

Your design:
![image](https://user-images.githubusercontent.com/12745474/153090114-cd287ef7-8b50-41f5-9497-7a1626c6ddbe.png)

**The wireframe design:**
![image](https://user-images.githubusercontent.com/12745474/134323111-24a1a54d-374a-4197-bdc5-7ddbbcc89636.png)

2022-02-08 23:10 UTC, rloterh commented on index.html
> +      <footer><p>Copyright: All rights reserved</p></footer>
- [ ] Kindly ensure that the text `Copyright`, and is aligned to the left of the _footer_. of each page.

**Your sample page:**
![image](https://user-images.githubusercontent.com/12745474/153090833-16883202-da39-4ea7-9c1c-8d86c646d7f2.png)


**The wireframe pages:**
![image](https://user-images.githubusercontent.com/12745474/138343768-db7df029-2766-4f6c-b59a-67fd2ac3deb3.png)

2022-02-09 18:36 UTC, Lameck1 approved these changes
Hi, @Estebanmual  & @sediqullahbadakhsh,

You've done well working on the concerns from the previous review 👏🏿.
The tasks for this final milestone are now successfully implemented 💯.
All the best with your next project.

You are free to merge this branch :shipit:

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 19:12 UTC, merged